create table if not exists public.watchlist (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    market_code varchar(20) not null,
    korean_name varchar(100) not null,
    english_name varchar(100) not null,
    created_at timestamptz not null default now(),
    constraint watchlist_user_market_unique unique (user_id, market_code)
);

create index if not exists watchlist_user_created_id_idx
    on public.watchlist (user_id, created_at asc, id asc);

alter table public.watchlist enable row level security;

create policy "Users can read own watchlist"
    on public.watchlist for select using (auth.uid() = user_id);

create policy "Users can insert own watchlist"
    on public.watchlist for insert with check (auth.uid() = user_id);

create policy "Users can delete own watchlist"
    on public.watchlist for delete using (auth.uid() = user_id);
