create type public.paper_transaction_type as enum ('INITIAL_GRANT','TOP_UP','BUY','SELL');
create type public.paper_asset_class as enum ('CRYPTO');

-- 7.1 paper_accounts
create table public.paper_accounts (
    user_id uuid primary key references auth.users(id) on delete cascade,
    cash_balance_krw bigint not null check (cash_balance_krw >= 0),
    lifetime_top_up_krw bigint not null default 0 check (lifetime_top_up_krw >= 0),
    created_at timestamptz not null default now()
);
alter table public.paper_accounts enable row level security;
create policy "select own account" on public.paper_accounts for select using (auth.uid() = user_id);
create policy "insert own account" on public.paper_accounts for insert with check (auth.uid() = user_id);
create policy "update own account" on public.paper_accounts for update using (auth.uid() = user_id);
revoke delete on public.paper_accounts from authenticated;
grant select, insert, update on public.paper_accounts to authenticated;

-- 7.2 paper_transactions (insert-only, immutable)
create table public.paper_transactions (
    id bigint generated by default as identity primary key,
    account_id uuid not null references public.paper_accounts(user_id) on delete cascade,
    type public.paper_transaction_type not null,
    asset_class public.paper_asset_class,
    market_code varchar(20),
    execution_price numeric(38,18),
    quantity numeric(38,18),
    cash_delta_krw bigint not null,
    balance_after_krw bigint not null,
    disposed_cost_basis_krw numeric(38,18),
    realized_pnl_krw numeric(38,18),
    quoted_at timestamptz,
    created_at timestamptz not null default now(),
    idempotency_key uuid,
    request_fingerprint char(64)
);
create index paper_transactions_account_id_desc_idx
    on public.paper_transactions (account_id, id desc);
create unique index paper_transactions_account_idem_unique_idx
    on public.paper_transactions (account_id, idempotency_key) where idempotency_key is not null;
create unique index paper_transactions_initial_grant_unique_idx
    on public.paper_transactions (account_id) where type = 'INITIAL_GRANT';
alter table public.paper_transactions enable row level security;
create policy "select own transactions" on public.paper_transactions for select using (auth.uid() = account_id);
create policy "insert own transactions" on public.paper_transactions for insert with check (auth.uid() = account_id);
revoke update, delete on public.paper_transactions from authenticated;
grant select, insert on public.paper_transactions to authenticated;

-- 7.3 paper_positions
create table public.paper_positions (
    id bigint generated by default as identity primary key,
    account_id uuid not null references public.paper_accounts(user_id) on delete cascade,
    asset_class public.paper_asset_class not null,
    market_code varchar(20) not null,
    quantity numeric(38,18) not null default 0 check (quantity >= 0),
    cost_basis_krw numeric(38,18) not null default 0 check (cost_basis_krw >= 0),
    realized_pnl_krw numeric(38,18) not null default 0,
    constraint paper_positions_account_market_unique unique (account_id, asset_class, market_code)
);
create index paper_positions_account_qty_positive_idx
    on public.paper_positions (account_id) where quantity > 0;
alter table public.paper_positions enable row level security;
create policy "select own positions" on public.paper_positions for select using (auth.uid() = account_id);
create policy "insert own positions" on public.paper_positions for insert with check (auth.uid() = account_id);
create policy "update own positions" on public.paper_positions for update using (auth.uid() = account_id);
revoke delete on public.paper_positions from authenticated;
grant select, insert, update on public.paper_positions to authenticated;
